UPOS_LABELS = [
    "ADJ",
    "ADP",
    "ADV",
    "AUX",
    "CCONJ",
    "DET",
    "INTJ",
    "NOUN",
    "NUM",
    "PART",
    "PRON",
    "PROPN",
    "PUNCT",
    "SCONJ",
    "SYM",
    "VERB",
    "X",
]

LANG_2_TREEBANK = {
    "ar": "UD_Arabic-PADT",
    "de": "UD_German-GSD",
    "en": "UD_English-EWT",
    "es": "UD_Spanish-GSD",
    "fi": "UD_Finnish-FTB",
    "fr": "UD_French-GSD",
    "hi": "UD_Hindi-HDTB",
    "id": "UD_Indonesian-GSD",
    "it": "UD_Italian-ISDT",
    "ja": "UD_Japanese-GSD",
    "ko": "UD_Korean-Kaist",
    "pt": "UD_Portuguese-GSD",
    "ru": "UD_Russian-SynTagRus",
    "th": "UD_Thai-PUD",
    "tr": "UD_Turkish-IMST",
    "zh": "UD_Chinese-GSD",
}

LANG_2_PUD = {
    "ar": "UD_Arabic-PUD",
    "de": "UD_German-PUD",
    "en": "UD_English-PUD",
    "es": "UD_Spanish-PUD",
    "fi": "UD_Finnish-PUD",
    "fr": "UD_French-PUD",
    "hi": "UD_Hindi-PUD",
    "id": "UD_Indonesian-PUD",
    "it": "UD_Italian-PUD",
    "ja": "UD_Japanese-PUD",
    "ko": "UD_Korean-PUD",
    "pt": "UD_Portuguese-PUD",
    "ru": "UD_Russian-PUD",
    "th": "UD_Thai-PUD",
    "tr": "UD_Turkish-PUD",
    "zh": "UD_Chinese-PUD",
}
